# Constants for hazard definition

# hazard subtypes directly taken from EMDAT
hazard_all_subtype_emdat = [
    "drought",
    "wildfire",
    "forest fire",
    "land fire",
    "ground movement",
    "tsunami",
    "avalanche",
    "landslide",
    "rockfall",
    "sudden subsidence",
    "mudslide",
    "ash fall",
    "lava flow",
    "pyroclastic flow",
    "lahar",
    "coastal flood",
    "flash flood",
    "riverine flood",
    "ice jam flood",
    "rogue wave",
    "seiche",
    "coldwave",
    "heatwave",
    "severe winter conditions",
    "derecho",
    "hail",
    "lightning",
    "winterstorm",
    "storm surge",
    "tornado",
    "extra-tropical storm",
    "tropical storm",
]

hazard_kw_reclass = {
    "Drought": r"\bdrought.*|\bdry\s+spell.*",
    "Wildfire": r"\b(forest\s*fire|wild\s*fire|land\s*fire|bush\s*fire|wildfire|landfire|bushfire|fire)s?\b.*",
    "Earthquake": r"\b(earthquake|ground\s+movement|tsunami)s?\b.*",
    "Mass movement": r"\b(mass\s+movement|avalanche|land\s*slide|landslide|rockfall|sudden\s+subsidence|mudslide|rockslide)s?\b.*",
    "Volcanic activity": r"\b(volcanic|ash\s+fall|lava\s+flow|pyroclastic\s+flow|lahar)s?\b.*",
    "Flood": r"\b(flood|inundation|coastal\s+flood|flash\s+flood|riverine\s+flood|ice\s+jam\s+flood|heavy rain)s?\b.*",
    "Wave action": r"\b((?<!cold\s)(?<!heat\s)wave|rogue\s+wave|seiche)s?\b.*",
    "Extreme cold temperature": r"\b(extreme\s+cold\s+temperature|cold\s+wave|coldwave|cold\s+spell|severe\s+winter\s+conditions)s?\b.*",
    "Extreme warm temperature": r"\b(extreme\s+warm\s+temperature|heat\s+wave|heatwave|heat\s+episode|(?:heat|hot)\s+spell|heat\s+stress)s?\b.*",
    "Tropical storm": r"\b(tropical\s+storm|typhoon|hurricane|cyclonic\s+storm)s?\b.*",
    "Convective storm": r"\b(convective\s+storm|derecho|hail|hail\s+storm|lightning|tornadoe?|superstorm|thunderstorm)s?\b.*",
    "Other storm": r"\b(Other\s+storm|extra-?tropical\s+storm|winter\s*storm|storm\s+surge|wind\s*storm|snow\s*storm|blizzard)s?\b.*",
    "Epidemic": r"\b(cholera|dengue|outbreak|epidemic)s?\b.*",
    "Conflict": r"\b(conflict|war|terrorism|unrest)s?\b.*",
}

hazard_ifrc_go = [
    "Flood",
    "Fire",
    "Cold Wave",
    "Earthquake",
    "Pluvial/Flash Flood",
    "Other",
    "Cyclone",
    "Drought",
    "Heat Wave",
    "Landslide",
    "Storm Surge",
    "Volcanic Eruption",
    "Tsunami",
]

hazard_main_types_emdat_desc = {
    "Drought": "Prolonged lack of precipitation",
    "Wildfire": "Uncontrolled natural fires",
    "Earthquake": "Sudden tectonic shifting. Include as well tsunami",
    "Mass movement": "Any type of downslope movement of earth materials. Includes Landslides and rockfalls",
    "Volcanic activity": "Eruptions and related phenomena",
    "Flood": "River, coastal, flash and ice jam flooding",
    "Wave action": "Wind-generated surface waves (e.g. Rogue waves, seiche)",
    "Extreme warm temperature": "Prolonged, abnormally high heat, heatwaves",
    "Extreme cold temperature": "Prolonged, abnormally low cold temperatures, coldwaves",
    "Convective storm": "Convective storms (e.g. tornadoes, thunderstorms, derechos, hailstorms...)",
    "Other storm": "Any type of storm which does not correspond to a tropical cyclone or a convective storm (e.g. extra-tropical storm, snow storm, ...)",
    "Tropical storm": "Tropical cyclonic storms (also includes hurricanes, typhoons)",
    "Epidemic": "Widespread occurrence of an infectious disease in a community",
    "Conflict": "Disagreements or disputes between different groups, organizations, or states",
}

hazard_mapping_emdat = {
    "Drought": ["Drought"],
    "Wildfire": [
        "Wildfire",
        "forest fire",
        "Forest fire",
        "land fire",
        "Land fire",
        "fire",
    ],
    "Earthquake": ["Earthquake", "Tsunami"],
    "Mass movement": [
        "Mass movement",
        "Mass movement (dry)",
        "Mass movement (wet)",
        "Landslide",
        "Mud flow/slide",
        "Avalanche",
        "Alluvion",
        "Coastal erosion",
        "Subsidence",
        "Erosion",
        "Sedimentation",
    ],
    "Volcanic activity": ["Volcanic activity", "Eruption", "Liquefaction", "Lahar"],
    "Flood": [
        "Flood",
        "Glacial lake outburst flood",
        "Flash flood",
        "Riverine flood",
        "Coastal flood",
        "Ice jam flood",
        "Rain",
        "Heavy rain",
        "Heavy rains",
        "Overflow",
    ],
    "Wave action": ["rogue wave", "seiche"],
    "Extreme temperature": [
        "Extreme warm temperature",
        "Extreme cold temperature",
        "Extreme temperature",
        "Cold wave",
        "Heat wave",
        "Severe winter conditions",
        "Frost",
    ],
    "Storm": [
        "Storm",
        "Other storm",
        "Tropical storm",
        "Convective storm",
        "Extra-tropical cyclone",
        "Severe local storm",
        "Violent wind",
        "Lightning",
        "Hail",
        "Storm surge",
        "Storm tides",
        "Tornado",
        "Tropical cyclone",
        "Fog",
        "Blizzard",
        "Windstorm",
        "Electric storm",
        "Snowstorm",
        "Hail storm",
        "Cyclone",
        "Surge",
        "Cond.Atmosph.",
        "Atmospheric cond.",
        "Sandstorm",
        "Tropical depression",
        "Atmosphcondition",
        "Strong wind",
    ],
}

hazard_to_emdat_undrr = {
    "Cold wave": ["nat-met-ext-col", "MH0040"],
    "Drought": ["nat-cli-dro-dro", "MH0035"],
    "Earthquake": ["nat-geo-ear-gro", "GH0001", "GH0002", "GH0003", "GH0004", "GH0005"],
    "Disease": [
        "nat-bio-epi-vir",
        "nat-bio-epi-bac",
        "nat-bio-epi-par",
        "nat-bio-epi-fun",
        "nat-bio-epi-pri",
        "nat-bio-epi-dis",
        "BI0016",
    ],
    "Extra-tropical cyclone": ["nat-met-sto-ext", "MH0031", "MH0099"],
    "Flash flood": ["nat-hyd-flo-fla", "MH0006"],
    "Riverine flood": ["nat-hyd-flo-riv", "MH0007"],
    "Coastal flood": ["nat-hyd-flo-coa", "MH0004"],
    "Flood": [
        "nat-hyd-flo-flo",
        "MH0012",
        "MH0008",
        "MH0010",
        "MH0011",
        "tec-mis-col-col",
        "TL0009",
    ],
    "Ice jam flood": ["nat-hyd-flo-ice", "MH0009"],
    "Glacial lake outburst flood": ["nat-cli-glo-glo", "MH0013"],
    "Heat wave": ["nat-met-ext-hea", "MH0047"],
    "Infection": [
        "nat-bio-inf-loc",
        "nat-bio-inf-gra",
        "nat-bio-inf-wor",
        "nat-bio-inf-inf",
        "BI0002",
        "BI0003",
    ],
    "Landslide": ["nat-geo-mmd-lan", "nat-hyd-mmw-lan", "GH0007", "GH0014"],
    "Mud flow/slide": ["nat-hyd-mmw-mud", "MH0051"],
    "Severe local storm": ["nat-met-sto-sto", "MH0003"],
    "Violent wind": ["MH0060"],
    "Lightning": ["nat-met-sto-lig", "MH0002"],
    "Hail": ["nat-met-sto-hai", "MH0036"],
    "Avalanche": ["nat-geo-mmd-ava", "nat-hyd-mmw-ava", "MH0050"],
    "Storm surge": ["nat-met-sto-sur", "MH0027"],
    "Storm tides": ["nat-hyd-wav-rog", "MH0028"],
    "Tornado": ["nat-met-sto-tor", "MH0059"],
    "Tropical cyclone": ["nat-met-sto-tro", "MH0057", "MH0058", "MH0030", "MH0032"],
    "Tsunami": ["nat-geo-ear-tsu", "MH0029", "GH0006", "GH0017", "GH0035"],
    "Volcanic activity": [
        "nat-geo-vol-lav",
        "GH0009",
        "nat-geo-vol-ash",
        "GH0010",
        "nat-geo-vol-vol",
        "GH0016",
        "nat-geo-vol-pyr",
        "GH0012",
        "nat-geo-vol-lah",
        "GH0013",
    ],
    "Forest fire": ["nat-cli-wil-for"],
    "Land fire": ["nat-cli-wil-lan"],
    "Wildfire": ["nat-cli-wil-wil", "EN0013"],
    "Conflict": ["Multiple codes", "SO0001", "SO0002", "SO0003", "SO0004", "SO0005"],
    "Fog": ["nat-met-fog-fog", "MH0016"],
    "Severe winter conditions": [
        "nat-met-ext-sev",
        "MH0041",
        "MH0042",
        "MH0043",
        "MH0044",
        "MH0045",
        "MH0046",
        "MH0048",
        "MH0049",
    ],
    "Blizzard": ["nat-met-sto-bli", "MH0034"],
}

emdat_undrr_to_name = {
    code: hazard for hazard, codes in hazard_to_emdat_undrr.items() for code in codes
}

# dict to match emdat maintypes to there subtypes
maintype_to_subytpe_emdat = {
    "Drought": ["drought"],
    "Wildfire": ["wildfire", "forest fire", "land fire"],
    "Earthquake": ["ground movement", "tsunami"],
    "Mass movement": [
        "avalanche",
        "landslide",
        "rockfall",
        "sudden subsidence",
        "mudslide",
    ],
    "Volcanic activity": ["ash fall", "lava flow", "pyroclastic flow", "lahar"],
    "Flood": [
        "\\b(coastal flood",
        "flash flood",
        "riverine flood",
        "ice jam flood)\\b",
    ],
    "Wave action": ["rogue wave", "seiche"],
    "Extreme temperature": ["coldwave", "heatwave", "severe winter conditions"],
    "Storm": [
        "derecho",
        "hail",
        "lightning",
        "winterstorm",
        "storm surge",
        "tornado",
        "winter storm",
        "extra-tropical storm",
        "tropical storm",
    ],
}
